env:
  contexts:
    - name: "TheBurguer API"
      urls:
        - "http://localhost:3000"
  parameters:
    failOnError: true

jobs:
  - type: openapi
    parameters:
      apiFile: ""
      apiUrl: "http://localhost:3000/api/docs-json"
      targetUrl: "http://localhost:3000"
      customHeaders:
        - name: "Authorization"
          value: "Bearer ${JWT_TOKEN}"

  - type: activeScan
    parameters:
      maxRuleDurationInMins: 2

  - type: report
    parameters:
      template: "traditional-html"
      reportDir: "C:\\Users\\mathe\\Desktop\\TheBurguer\\backend\\security"
      reportFile: "dast-report.html"